# Generated by Django 4.2.1 on 2023-05-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_currency_course_price_course_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Facebook'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Instagram'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Youtube'),
        ),
    ]
